import { Character, Kanda, Story, FamilyTreeNode, MapLocation, ThemeBlock } from './types';

export const stats = [
  { value: '7', label: 'Sacred Kandas' },
  { value: '24,000', label: 'Shlokas of Adi Kavya' },
  { value: '14', label: 'Years of Exile' },
  { value: '500+', label: 'Recorded Tellings' },
];

export const characters: Character[] = [
  {
    id: 'rama',
    name: 'Rama',
    sanskrit: 'श्री राम',
    epithet: 'Maryada Purushottam · The Seventh Avatar of Vishnu',
    rarity: 'mythic',
    alignment: 'Dharma',
    affiliation: 'Kingdom of Kosala · House of Ikshvaku',
    origin: 'Ayodhya',
    era: 'Treta Yuga',
    weapon: 'Kodanda — the celestial longbow',
    glyph: '🏹',
    accent: '#3B82F6',
    stats: [
      { label: 'Valor', value: 98 },
      { label: 'Dharma', value: 100 },
      { label: 'Skill', value: 96 },
      { label: 'Wisdom', value: 92 },
    ],
    abilities: ['Brahmastra mastery', 'Unbroken oath-keeper', 'Inspires absolute loyalty', 'Strategist of righteous war'],
    quote: '“I will keep my father’s word, though it costs me the throne — for truth is the breath of kings.”',
    lore: 'Born to King Dasharatha and Queen Kausalya, Rama is the seventh avatar of Vishnu, descended to end the tyranny of Ravana. His life is a living scripture on duty — as a son, husband, brother, and king. Every choice he makes becomes a measuring rod of dharma for ages to follow.',
    keyMoments: [
      { title: 'Breaking Shiva’s Bow', kanda: 'Bala Kanda', description: 'Wins Sita’s hand at Janaka’s court by lifting and stringing the Pinaka, a feat no king on earth could perform.' },
      { title: 'Accepting Exile', kanda: 'Ayodhya Kanda', description: 'On the eve of his coronation, Rama silently accepts 14 years of forest exile to honor his father’s word to Kaikeyi.' },
      { title: 'Slaying Khara & Dushana', kanda: 'Aranya Kanda', description: 'Alone, he routs an army of fourteen thousand rakshasas — the first tremor that shakes Lanka.' },
      { title: 'The Fall of Ravana', kanda: 'Yuddha Kanda', description: 'On the final day of war, the Brahmastra blessed by Agastya pierces the ten-headed king’s heart.' },
      { title: 'Coronation of Ramarajya', kanda: 'Yuddha Kanda', description: 'Returns to Ayodhya on Pushpaka Vimana; his reign becomes the eternal symbol of a just kingdom.' },
    ],
  },
  {
    id: 'sita',
    name: 'Sita',
    sanskrit: 'सीता देवी',
    epithet: 'Janaki · Avatar of Lakshmi, Daughter of the Earth',
    rarity: 'mythic',
    alignment: 'Dharma',
    affiliation: 'Kingdom of Mithila · Consort of Rama',
    origin: 'A furrow of the sacred field',
    era: 'Treta Yuga',
    weapon: 'Inner fire of chastity (Tejas)',
    glyph: '🪷',
    accent: '#E879F9',
    stats: [
      { label: 'Resolve', value: 100 },
      { label: 'Grace', value: 98 },
      { label: 'Wisdom', value: 94 },
      { label: 'Tejas', value: 99 },
    ],
    abilities: ['Unshakable fidelity', 'Speaks truth to power', 'Earth-born endurance', 'Commands fire itself'],
    quote: '“The forest at Rama’s side is sweeter than a palace without him.”',
    lore: 'Born of the earth and discovered by King Janaka, Sita is no ordinary queen. She chooses exile over palace, defies a ten-headed emperor with a blade of grass between them, and walks through fire to silence a kingdom. The Ramayana is, at its heart, her story.',
    keyMoments: [
      { title: 'The Swayamvara', kanda: 'Bala Kanda', description: 'Garlands Rama after he lifts the bow of Shiva — a marriage ordained by heaven.' },
      { title: 'Choosing the Forest', kanda: 'Ayodhya Kanda', description: 'Refuses the throne and follows Rama into 14 years of wilderness.' },
      { title: 'Resisting Ravana', kanda: 'Sundara Kanda', description: 'For a year in Ashoka Vatika, she refuses the demon-king with only her dharma as armor.' },
      { title: 'Agni Pariksha', kanda: 'Yuddha Kanda', description: 'Walks unburnt through fire — Agni himself returns her to Rama, untouched.' },
      { title: 'Return to the Earth', kanda: 'Uttara Kanda', description: 'After a second exile, she calls upon her mother Bhumi, who opens to receive her home.' },
    ],
  },
  {
    id: 'hanuman',
    name: 'Hanuman',
    sanskrit: 'हनुमान',
    epithet: 'Bajrangbali · Son of the Wind, Eternal Devotee',
    rarity: 'legendary',
    alignment: 'Dharma',
    affiliation: 'Kishkindha · Servant of Rama',
    origin: 'Anjaneya, born of Anjana and Vayu',
    era: 'Treta Yuga',
    weapon: 'Gada (mace) and immeasurable strength',
    glyph: '⚡',
    accent: '#F59E0B',
    stats: [
      { label: 'Strength', value: 100 },
      { label: 'Devotion', value: 100 },
      { label: 'Speed', value: 98 },
      { label: 'Intellect', value: 95 },
    ],
    abilities: ['Shape-shifting (Kamarupi)', 'Leaps across oceans', 'Immortal (Chiranjivi)', 'Brahmastra-immune by boon'],
    quote: '“Wherever Rama’s name is sung, there I am — listening with folded hands.”',
    lore: 'A vanara prince who once swallowed the sun mistaking it for fruit. Cursed to forget his powers until reminded, Hanuman becomes the perfect devotee — strong only when invoked in service. He is the bridge between Rama and the impossible.',
    keyMoments: [
      { title: 'Awakening at the Shore', kanda: 'Kishkindha Kanda', description: 'Jambavan reminds Hanuman of his powers; he expands to mountain-size before the leap.' },
      { title: 'The Leap to Lanka', kanda: 'Sundara Kanda', description: 'Crosses 100 yojanas of ocean in a single bound, defeating Surasa and Simhika mid-flight.' },
      { title: 'Finding Sita', kanda: 'Sundara Kanda', description: 'Slips into Ashoka Vatika, offers Rama’s ring, and pledges to bring the army.' },
      { title: 'Lanka Dahan', kanda: 'Sundara Kanda', description: 'Tail set aflame by Ravana, he leaps roof to roof and turns the golden city to ash.' },
      { title: 'The Sanjeevani Mountain', kanda: 'Yuddha Kanda', description: 'Unable to find the herb, he uproots the entire Himalayan peak and flies it to Lakshmana’s side.' },
    ],
  },
  {
    id: 'ravana',
    name: 'Ravana',
    sanskrit: 'रावण',
    epithet: 'Dashanan · Emperor of Lanka, the Tragic Tyrant',
    rarity: 'legendary',
    alignment: 'Adharma',
    affiliation: 'Rakshasa Empire of Lanka',
    origin: 'Grandson of Pulastya, devotee of Shiva',
    era: 'Treta Yuga',
    weapon: 'Chandrahas — the moon-blade gifted by Shiva',
    glyph: '👑',
    accent: '#B91C1C',
    stats: [
      { label: 'Power', value: 97 },
      { label: 'Scholarship', value: 96 },
      { label: 'Ambition', value: 100 },
      { label: 'Dharma', value: 22 },
    ],
    abilities: ['Master of the Vedas & Tantra', 'Boon of near-invincibility', 'Wields the Brahmastra', 'Composer of Shiva Tandava Stotram'],
    quote: '“Even gods may bow to me — but a forest-dwelling prince I shall not fear.”',
    lore: 'The most learned king of his age — astronomer, musician, statesman — yet undone by a single appetite. Ravana’s tragedy is the warning at the heart of the Ramayana: that knowledge without humility is the fastest road to ruin.',
    keyMoments: [
      { title: 'Lifting Mount Kailash', kanda: 'Uttara Kanda', description: 'In hubris he tries to uproot Shiva’s mountain; pinned by a single toe, he composes the Tandava Stotram in repentance.' },
      { title: 'Boon from Brahma', kanda: 'Uttara Kanda', description: 'Wins immunity from gods, demons, and beasts — forgetting only to ask protection from men.' },
      { title: 'Abduction of Sita', kanda: 'Aranya Kanda', description: 'Disguised as a wandering ascetic, he carries her across the sky in the Pushpaka Vimana.' },
      { title: 'Sending Kumbhakarna', kanda: 'Yuddha Kanda', description: 'Wakes his giant brother from six-month sleep to face the vanara host.' },
      { title: 'Final Duel with Rama', kanda: 'Yuddha Kanda', description: 'Heads regrow until Rama strikes the navel where amrita is hidden — the war ends in one arrow.' },
    ],
  },
  {
    id: 'lakshmana',
    name: 'Lakshmana',
    sanskrit: 'लक्ष्मण',
    epithet: 'Sheshnaga Avatar · The Shadow of Rama',
    rarity: 'legendary',
    alignment: 'Dharma',
    affiliation: 'House of Ikshvaku · Brother of Rama',
    origin: 'Son of Dasharatha and Sumitra',
    era: 'Treta Yuga',
    weapon: 'Bow and the celestial Anjalika arrow',
    glyph: '⚔️',
    accent: '#10B981',
    stats: [
      { label: 'Loyalty', value: 100 },
      { label: 'Valor', value: 95 },
      { label: 'Discipline', value: 98 },
      { label: 'Wrath', value: 92 },
    ],
    abilities: ['Slept not for 14 years', 'Slayer of Indrajit', 'Master of the Lakshman Rekha', 'Incarnation of Shesha'],
    quote: '“Where my brother walks, my bowstring sings.”',
    lore: 'The incarnation of the cosmic serpent Shesha, Lakshmana chooses to serve rather than rule. He gives up sleep, food, and his own kingdom to guard Rama and Sita for fourteen years — a vow no mortal could keep.',
    keyMoments: [
      { title: 'Following Rama Into Exile', kanda: 'Ayodhya Kanda', description: 'Leaves his wife Urmila and the palace without hesitation when Rama is banished.' },
      { title: 'Punishing Surpanakha', kanda: 'Aranya Kanda', description: 'Cuts off the nose of Ravana’s sister when she threatens Sita — sparking the war.' },
      { title: 'The Lakshman Rekha', kanda: 'Aranya Kanda', description: 'Draws the protective line around Sita before reluctantly leaving to find Rama.' },
      { title: 'Killing Indrajit', kanda: 'Yuddha Kanda', description: 'In Lanka, slays Ravana’s invincible son — the only one who could have turned the war.' },
      { title: 'The Sleeping Wound', kanda: 'Yuddha Kanda', description: 'Falls to Ravana’s Shakti weapon and is revived only by Sanjeevani brought by Hanuman.' },
    ],
  },
  {
    id: 'bharata',
    name: 'Bharata',
    sanskrit: 'भरत',
    epithet: 'Padukadhari · The Regent of Sandals',
    rarity: 'epic',
    alignment: 'Dharma',
    affiliation: 'House of Ikshvaku · Son of Kaikeyi',
    origin: 'Ayodhya',
    era: 'Treta Yuga',
    weapon: 'Bow of Kosala',
    glyph: '👡',
    accent: '#F5D061',
    stats: [
      { label: 'Honor', value: 100 },
      { label: 'Renunciation', value: 98 },
      { label: 'Statecraft', value: 93 },
      { label: 'Devotion', value: 99 },
    ],
    abilities: ['Refuses an unearned throne', 'Rules as ascetic-regent for 14 years', 'Master of dharmic governance'],
    quote: '“These sandals are my king. I am only their servant.”',
    lore: 'Offered the throne his mother schemed for, Bharata refuses it utterly. He rules from a hut in Nandigram with Rama’s wooden sandals upon the seat of power, proving that true authority is a trust, never a possession.',
    keyMoments: [
      { title: 'Refusing the Throne', kanda: 'Ayodhya Kanda', description: 'On returning from Kekeya, denounces his mother’s scheme and rushes to bring Rama back.' },
      { title: 'Meeting at Chitrakuta', kanda: 'Ayodhya Kanda', description: 'Pleads with Rama to return; Rama gives his sandals as proxy regent.' },
      { title: 'The Reign at Nandigram', kanda: 'Ayodhya Kanda', description: 'For 14 years he wears bark, eats forest food, and signs every order in Rama’s name.' },
      { title: 'Welcoming Rama Home', kanda: 'Yuddha Kanda', description: 'Greets the returning party with the sandals on his head — kingdom restored, untouched.' },
    ],
  },
  {
    id: 'sugriva',
    name: 'Sugriva',
    sanskrit: 'सुग्रीव',
    epithet: 'King of Kishkindha · The Sunlit Ape',
    rarity: 'epic',
    alignment: 'Dharma',
    affiliation: 'Vanara Empire',
    origin: 'Son of Surya, brother of Vali',
    era: 'Treta Yuga',
    weapon: 'Tree-trunk mace, jaw-fang strike',
    glyph: '🦍',
    accent: '#FBBF24',
    stats: [
      { label: 'Loyalty', value: 90 },
      { label: 'Strength', value: 92 },
      { label: 'Leadership', value: 88 },
      { label: 'Speed', value: 90 },
    ],
    abilities: ['Commander of the vanara host', 'Sun-blessed vigor', 'Map-knower of every realm'],
    quote: '“Bind our friendship in fire — I shall not rest till Sita is found.”',
    lore: 'Exiled by his elder brother Vali, Sugriva meets Rama on Rishyamukha and forges a pact of fire-witnessed friendship. With his throne restored, he raises the army that will cross an ocean.',
    keyMoments: [
      { title: 'Pact of Friendship', kanda: 'Kishkindha Kanda', description: 'Around a sacred fire, swears alliance with Rama in exchange for justice against Vali.' },
      { title: 'The Forgotten Promise', kanda: 'Kishkindha Kanda', description: 'Lost in coronation revels until Lakshmana’s wrath shakes him awake.' },
      { title: 'Dispatching the Search Parties', kanda: 'Kishkindha Kanda', description: 'Sends vanara captains to the four directions — Hanuman to the south.' },
      { title: 'Crossing the Setu', kanda: 'Yuddha Kanda', description: 'Marches his entire army over the floating bridge to Lanka.' },
    ],
  },
  {
    id: 'vibhishana',
    name: 'Vibhishana',
    sanskrit: 'विभीषण',
    epithet: 'The Rakshasa Who Chose Dharma',
    rarity: 'epic',
    alignment: 'Dharma',
    affiliation: 'Lanka (defector) · House of Pulastya',
    origin: 'Brother of Ravana and Kumbhakarna',
    era: 'Treta Yuga',
    weapon: 'Sword & strategic mind',
    glyph: '🕊️',
    accent: '#A5B4FC',
    stats: [
      { label: 'Wisdom', value: 95 },
      { label: 'Conscience', value: 100 },
      { label: 'Strategy', value: 92 },
      { label: 'Courage', value: 90 },
    ],
    abilities: ['Knows every secret of Lanka', 'Boon of long rule', 'Master of dharmic counsel'],
    quote: '“A brother in error must be opposed, not obeyed.”',
    lore: 'Born a rakshasa but raised on the Vedas, Vibhishana warns Ravana against keeping Sita. Banished for his honesty, he crosses to Rama — and is crowned future king of Lanka before the war even begins.',
    keyMoments: [
      { title: 'The Council of Lanka', kanda: 'Yuddha Kanda', description: 'Openly urges Ravana to return Sita; is kicked from court for his counsel.' },
      { title: 'Crossing to Rama', kanda: 'Yuddha Kanda', description: 'Surrenders at Rama’s camp; Rama accepts him under the law of refuge.' },
      { title: 'Revealing Ravana’s Secret', kanda: 'Yuddha Kanda', description: 'Tells Rama that the amrita lies in his brother’s navel — the final clue of the war.' },
      { title: 'Coronation in Lanka', kanda: 'Yuddha Kanda', description: 'After the battle, crowned king on the ashes of his brother’s palace.' },
    ],
  },
  {
    id: 'jatayu',
    name: 'Jatayu',
    sanskrit: 'जटायु',
    epithet: 'The Vulture King · Friend of Dasharatha',
    rarity: 'rare',
    alignment: 'Dharma',
    affiliation: 'Bird Kingdoms',
    origin: 'Son of Aruna',
    era: 'Treta Yuga',
    weapon: 'Beak and talons of steel',
    glyph: '🦅',
    accent: '#94A3B8',
    stats: [
      { label: 'Valor', value: 92 },
      { label: 'Loyalty', value: 100 },
      { label: 'Speed', value: 95 },
      { label: 'Age', value: 99 },
    ],
    abilities: ['Aerial combat master', 'Eyes that see across yojanas', 'Last guardian of the sky'],
    quote: '“Stop, demon — while these wings still beat, Sita shall not be yours.”',
    lore: 'The ancient vulture-king and friend of King Dasharatha. When Ravana’s chariot streaks across the sky with Sita, only Jatayu rises to fight — and pays with his life so Rama would know the way south.',
    keyMoments: [
      { title: 'Battle in the Sky', kanda: 'Aranya Kanda', description: 'Tears at Ravana’s chariot until his wings are clipped by the moon-blade.' },
      { title: 'Last Breath for Rama', kanda: 'Aranya Kanda', description: 'Lives just long enough to whisper that Sita was taken southward, then attains liberation in Rama’s arms.' },
    ],
  },
  {
    id: 'indrajit',
    name: 'Indrajit',
    sanskrit: 'इन्द्रजित',
    epithet: 'Meghnad · Conqueror of Indra',
    rarity: 'epic',
    alignment: 'Adharma',
    affiliation: 'Lanka · Crown Prince',
    origin: 'Son of Ravana and Mandodari',
    era: 'Treta Yuga',
    weapon: 'Brahmastra, Vaishnavastra, Pashupatastra',
    glyph: '🌩️',
    accent: '#7C3AED',
    stats: [
      { label: 'Sorcery', value: 99 },
      { label: 'Skill', value: 97 },
      { label: 'Stealth', value: 96 },
      { label: 'Pride', value: 95 },
    ],
    abilities: ['Invisibility in battle', 'All three ultimate astras', 'Performs yajna for invincibility'],
    quote: '“I have humbled the gods; mortal flesh is nothing to me.”',
    lore: 'The only being to defeat Indra in open battle. Wielder of the three supreme weapons, his maya nearly ends the war for Lanka — until Lakshmana interrupts his final yajna and breaks the boon.',
    keyMoments: [
      { title: 'Binding Rama & Lakshmana', kanda: 'Yuddha Kanda', description: 'Strikes both princes with the Nagapasha; Garuda must descend to free them.' },
      { title: 'The Illusion of Sita’s Death', kanda: 'Yuddha Kanda', description: 'Conjures a phantom Sita and slays her before the vanara host to break their morale.' },
      { title: 'Death at Nikumbhila', kanda: 'Yuddha Kanda', description: 'Vibhishana leads Lakshmana to his secret yajna; the rite broken, he is slain mid-prayer.' },
    ],
  },
  {
    id: 'kumbhakarna',
    name: 'Kumbhakarna',
    sanskrit: 'कुम्भकर्ण',
    epithet: 'The Pot-Eared Giant · Sleeping Mountain',
    rarity: 'epic',
    alignment: 'Adharma',
    affiliation: 'Lanka · Brother of Ravana',
    origin: 'Son of Vishrava and Kaikesi',
    era: 'Treta Yuga',
    weapon: 'Mountain-club, raw devouring strength',
    glyph: '🏔️',
    accent: '#78716C',
    stats: [
      { label: 'Strength', value: 99 },
      { label: 'Endurance', value: 100 },
      { label: 'Honor', value: 80 },
      { label: 'Speed', value: 60 },
    ],
    abilities: ['Sleeps six months, devours six', 'Mountain-shattering blows', 'Boon-cursed slumber'],
    quote: '“My brother is wrong — yet my brother is my king. I march.”',
    lore: 'A scholar who, by a slip of the tongue while begging boons from Brahma, asked for endless sleep instead of conquest. Loyal beyond reason, he wakes to die in a war he never wanted.',
    keyMoments: [
      { title: 'The Awakening', kanda: 'Yuddha Kanda', description: 'A thousand drums, elephants, and feasts are required to rouse him from slumber.' },
      { title: 'Devouring the Vanara Host', kanda: 'Yuddha Kanda', description: 'Sweeps up monkeys by the dozen until Sugriva himself charges to stop him.' },
      { title: 'Falling to Rama', kanda: 'Yuddha Kanda', description: 'Limbs severed by celestial arrows, his head finally falls into the sea.' },
    ],
  },
  {
    id: 'vishwamitra',
    name: 'Vishwamitra',
    sanskrit: 'विश्वामित्र',
    epithet: 'The Warrior-Sage · Maker of New Heavens',
    rarity: 'epic',
    alignment: 'Dharma',
    affiliation: 'Brahmarishi · Royal Sage of Ayodhya',
    origin: 'Once King Kaushika, became a Brahmarishi by tapasya',
    era: 'Treta Yuga',
    weapon: 'Astras of every god',
    glyph: '🔱',
    accent: '#FB923C',
    stats: [
      { label: 'Tapas', value: 100 },
      { label: 'Knowledge', value: 98 },
      { label: 'Will', value: 100 },
      { label: 'Wrath', value: 90 },
    ],
    abilities: ['Knows every divine astra', 'Created a parallel heaven for Trishanku', 'Initiates Rama into cosmic weapons'],
    quote: '“Rise, prince of Raghu — the world has need of arrows that do not miss.”',
    lore: 'A king who renounced his throne to become a Brahmarishi. He arrives at Ayodhya to claim Rama and Lakshmana as his protectors, and in return gifts them the secret mantras of every divine weapon.',
    keyMoments: [
      { title: 'Taking Rama from Ayodhya', kanda: 'Bala Kanda', description: 'Convinces Dasharatha to send Rama and Lakshmana to guard his yajna.' },
      { title: 'Teaching the Astras', kanda: 'Bala Kanda', description: 'Initiates the boys into Bala and Atibala — they need no food, no sleep, no weariness.' },
      { title: 'Leading to Mithila', kanda: 'Bala Kanda', description: 'Brings Rama to Janaka’s court — where the bow of Shiva awaits.' },
    ],
  },
];

export const kandas: Kanda[] = [
  {
    title: 'Bala Kanda',
    sanskrit: 'बाल काण्ड',
    subtitle: 'The Book of Youth',
    description: 'Divine births, the sage Vishwamitra’s call, the slaying of demons, and the breaking of Shiva’s bow that wins Sita.',
    theme: 'Divine Advent · Heroic Childhood',
    accent: '#FF8C42',
    keyEvents: [
      'Birth of Rama, Lakshmana, Bharata, and Shatrughna.',
      'Vishwamitra trains the princes and they slay Tataka and Subahu.',
      'Rama lifts the bow of Shiva and weds Sita at Janaka’s court.',
    ],
    majorCharacters: ['Rama', 'Lakshmana', 'Bharata', 'Shatrughna', 'Vishwamitra', 'Sita', 'Janaka', 'Dasharatha'],
  },
  {
    title: 'Ayodhya Kanda',
    sanskrit: 'अयोध्या काण्ड',
    subtitle: 'The Book of the Royal City',
    description: 'A queen’s two boons, a prince’s silent renunciation, a kingdom’s grief — and Bharata’s sandal-throne in Nandigram.',
    theme: 'Sacrifice · Duty · Renunciation',
    accent: '#D4AF37',
    keyEvents: [
      'Dasharatha announces Rama’s coronation.',
      'Kaikeyi, swayed by Manthara, demands her boons.',
      'Rama accepts 14 years of exile to honor his father.',
      'Bharata rules from Nandigram with Rama’s sandals on the throne.',
    ],
    majorCharacters: ['Rama', 'Sita', 'Lakshmana', 'Bharata', 'Dasharatha', 'Kaikeyi', 'Kausalya', 'Manthara'],
  },
  {
    title: 'Aranya Kanda',
    sanskrit: 'अरण्य काण्ड',
    subtitle: 'The Book of the Forest',
    description: 'Forest hermitages, the humbling of Surpanakha, the golden deer, and the abduction that turns the world.',
    theme: 'The Turning of Fate',
    accent: '#10B981',
    keyEvents: [
      'Life in the Dandaka forest with the sages.',
      'Surpanakha is rebuffed; Khara and Dushana fall.',
      'Maricha takes the form of a golden deer.',
      'Ravana abducts Sita; Jatayu falls fighting in the sky.',
    ],
    majorCharacters: ['Rama', 'Lakshmana', 'Sita', 'Jatayu', 'Surpanakha', 'Maricha', 'Ravana'],
  },
  {
    title: 'Kishkindha Kanda',
    sanskrit: 'किष्किन्धा काण्ड',
    subtitle: 'The Book of the Vanara Realm',
    description: 'Friendship sealed in fire, a brother slain from cover, and a vanara army turned to the four directions in search of Sita.',
    theme: 'Alliance · Moral Complexity',
    accent: '#FBBF24',
    keyEvents: [
      'Rama meets Hanuman and Sugriva on Rishyamukha.',
      'Pact of friendship sealed around the sacred fire.',
      'Vali is slain; Sugriva is crowned in Kishkindha.',
      'Vanara search parties dispatched to the four corners.',
    ],
    majorCharacters: ['Rama', 'Lakshmana', 'Hanuman', 'Sugriva', 'Vali', 'Jambavan', 'Tara'],
  },
  {
    title: 'Sundara Kanda',
    sanskrit: 'सुन्दर काण्ड',
    subtitle: 'The Book of Beauty',
    description: 'A single hero, a single leap. Hanuman crosses an ocean, finds a queen, and leaves a city in flames.',
    theme: 'Devotion · Heroism · Hope',
    accent: '#F59E0B',
    keyEvents: [
      'Hanuman leaps 100 yojanas across the southern sea.',
      'Defeats Surasa and Simhika in the air.',
      'Finds Sita in the Ashoka Vatika and delivers Rama’s ring.',
      'Burns the city of Lanka with his flaming tail.',
    ],
    majorCharacters: ['Hanuman', 'Sita', 'Ravana', 'Vibhishana', 'Trijata'],
  },
  {
    title: 'Yuddha Kanda',
    sanskrit: 'युद्ध काण्ड',
    subtitle: 'The Book of War',
    description: 'A bridge over the sea, the fall of giants, the duel of an age — and a queen walking through fire.',
    theme: 'The Final Reckoning',
    accent: '#B91C1C',
    keyEvents: [
      'The Ram Setu is built by Nala and Nila.',
      'Kumbhakarna and Indrajit are slain.',
      'Rama and Ravana duel; the Brahmastra finds its mark.',
      'Sita endures the Agni Pariksha and returns to Ayodhya.',
    ],
    majorCharacters: ['Rama', 'Lakshmana', 'Hanuman', 'Sugriva', 'Vibhishana', 'Ravana', 'Kumbhakarna', 'Indrajit', 'Sita'],
  },
  {
    title: 'Uttara Kanda',
    sanskrit: 'उत्तर काण्ड',
    subtitle: 'The Later Book',
    description: 'Ramarajya rises. A rumor whispers. Sita walks again into the forest, and at last into the open earth.',
    theme: 'Kingship · Sorrow · Liberation',
    accent: '#A78BFA',
    keyEvents: [
      'Ramarajya is established and praised across the world.',
      'A whispered rumor leads to Sita’s second exile.',
      'Lava and Kusha are born and raised in Valmiki’s ashram.',
      'Sita returns to the Earth; Rama prepares for Vaikuntha.',
    ],
    majorCharacters: ['Rama', 'Sita', 'Lakshmana', 'Valmiki', 'Lava', 'Kusha'],
  },
];

export const themesData: ThemeBlock[] = [
  {
    title: 'The Burden of Dharma',
    description: 'Righteousness is rarely a clean choice — Rama, Sita, Bharata, and even Ravana wrestle with duties that contradict one another.',
    glyph: '☸',
  },
  {
    title: 'The Human Face of the Divine',
    description: 'Avatars walk the earth with mortal grief, fear, and love. Their struggle is what makes their dharma believable.',
    glyph: '🪔',
  },
  {
    title: 'Devotion as Power',
    description: 'Hanuman, Lakshmana, Bharata — the epic insists that surrendered service can be mightier than any weapon.',
    glyph: '🕉',
  },
  {
    title: 'The Ideal of Ramarajya',
    description: 'A vision of governance where the ruler exists for the ruled — peace, justice, and prosperity for all beings.',
    glyph: '🏛',
  },
];

export const stories: Story[] = [
  { title: 'The Birth of the Princes', description: 'A divine yajna brings four sons to Dasharatha — and an avatar to the earth.', link: 'https://g.co/gemini/share/5219d589608e' },
  { title: 'The Gurukul of Vasishtha', description: 'Rama and his brothers learn the bow, the scripture, and the silence of sages.', link: 'https://g.co/gemini/share/de97aacba7c2' },
  { title: 'Sita’s Swayamvara', description: 'A bow no king could lift; a prince who lifts it without effort.', link: 'https://g.co/gemini/share/3ee98b861c00' },
  { title: 'The Royal Wedding', description: 'Four brothers, four brides — and a banquet that crowns two kingdoms.', link: 'https://g.co/gemini/share/3fb03b56be92' },
  { title: 'The Plot of Kaikeyi', description: 'A whispered grievance becomes the lever that moves an empire.', link: 'https://g.co/gemini/share/a3059de809aa' },
  { title: 'Rama’s Exile Begins', description: 'A prince, a princess, a brother — and the silence of the forest.', link: 'https://g.co/gemini/share/e8963612ada6' },
  { title: 'The Grief of Dasharatha', description: 'A father’s last breath calls for a son who cannot come.', link: 'https://g.co/gemini/share/6c9e0f158616' },
  { title: 'Bharata’s Devotion', description: 'He refuses a throne offered in blood and crowns a pair of sandals instead.', link: 'https://g.co/gemini/share/9051fa71bbdb' },
  { title: 'The Abduction of Sita', description: 'A golden deer, a cry for help, and a chariot in the sky.', link: 'https://g.co/gemini/share/234ae1bfffa7' },
  { title: 'Jatayu’s Last Flight', description: 'The old vulture-king rises one more time, for his friend’s daughter-in-law.', link: 'https://g.co/gemini/share/0a71f027ee83' },
  { title: 'The Search for Sita', description: 'A grieving Rama, a clever Hanuman, and an army drawn from the forest.', link: 'https://g.co/gemini/share/9cbd9d3ee0e9' },
  { title: 'The Leap to Lanka', description: 'A single bound that crosses an ocean — and a heart.', link: 'https://g.co/gemini/share/896b58c855fa' },
  { title: 'Hanuman in Lanka', description: 'A ring delivered, a garden destroyed, a city set ablaze.', link: 'https://g.co/gemini/share/f243c5c4c26c' },
  { title: 'The Bridge of Stones', description: 'Nala and Nila float boulders; the sea bows to a name.', link: 'https://g.co/gemini/share/7d811eb43e6e' },
  { title: 'The Great War', description: 'Astras across the sky, giants and sorcerers, and a brotherhood that holds.', link: 'https://g.co/gemini/share/c218d3ed5eba' },
  { title: 'The Fall of Ravana', description: 'A duel beyond endurance — and an arrow that finally finds the navel.', link: 'https://g.co/gemini/share/b52f9c5cd7a6' },
  { title: 'The Agni Pariksha', description: 'A queen walks through fire — and the fire walks her home.', link: 'https://g.co/gemini/share/8c9cfb2a6860' },
  { title: 'The Coronation of Rama', description: 'A city lit with a thousand diyas welcomes its king at last.', link: 'https://g.co/gemini/share/d58474a2a72d' },
];

export const familyTreeData: FamilyTreeNode = {
  name: 'Dasharatha',
  spouse: 'Kausalya · Kaikeyi · Sumitra',
  children: [
    { name: 'Rama', spouse: 'Sita', children: [{ name: 'Lava' }, { name: 'Kusha' }] },
    { name: 'Bharata', spouse: 'Mandavi' },
    { name: 'Lakshmana', spouse: 'Urmila' },
    { name: 'Shatrughna', spouse: 'Shrutakirti' },
  ],
};

export const mapLocations: MapLocation[] = [
  { id: 'ayodhya', name: 'Ayodhya', description: 'Capital of Kosala; birthplace of Rama. The story begins and ends here.', coords: { x: '55%', y: '25%' } },
  { id: 'mithila', name: 'Mithila', description: 'Janaka’s kingdom — where the bow of Shiva broke and a marriage was made.', coords: { x: '68%', y: '27%' } },
  { id: 'chitrakuta', name: 'Chitrakuta', description: 'The first forest hermitage; Bharata meets Rama here.', coords: { x: '52%', y: '40%' } },
  { id: 'dandaka', name: 'Dandaka Forest', description: 'A vast wild where most of the 14-year exile unfolds.', coords: { x: '50%', y: '52%' } },
  { id: 'panchavati', name: 'Panchavati', description: 'By the Godavari — where Sita was taken.', coords: { x: '42%', y: '60%' } },
  { id: 'kishkindha', name: 'Kishkindha', description: 'Vanara capital; the pact of fire-friendship is sworn here.', coords: { x: '48%', y: '76%' } },
  { id: 'rameshwaram', name: 'Rameshwaram', description: 'Southern shore from which the Ram Setu was built.', coords: { x: '53%', y: '88%' } },
  { id: 'lanka', name: 'Lanka', description: 'The golden city of Ravana — and the field of the final war.', coords: { x: '58%', y: '95%' } },
];
